### ISSUE TITLE
Uncaught TypeError: Cannot read property 'children' of null

### ISSUE THREAD

**Issue by externuz** [ericcornelissen/pinned-tabs-for-atom#18]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Ubuntu 16.04
**Thrown From**: [pinned-tabs](https://github.com/ericcornelissen/pinned-tabs-for-atom) package, v0.2.3

### Stack Trace

Uncaught TypeError: Cannot read property 'children' of null

```
At /home/externuz/.atom/packages/pinned-tabs/lib/pinned-tabs.coffee:129

TypeError: Cannot read property 'children' of null
    at /home/externuz/.atom/packages/pinned-tabs/lib/pinned-tabs.coffee:129:24
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.willDestroyPaneItem (/usr/share/atom/resources/app.asar/src/pane-container.js:298:27)
    at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app.asar/src/pane.js:630:17)
    at atom-tabs.TabBarView.onClick (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:688:17)
```

### Commands

```
     -3:30.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -3:29.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -3:23.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:21.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:21.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -3:20.8.0 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -3:20.8.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -3:20.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -3:20.1.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -3:20.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -3:20.1.0 editor:indent (atom-text-editor.editor.is-focused)
  3x -3:19.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:15.1.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:14.6.0 core:save (atom-text-editor.editor.is-focused)
     -3:02.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:01.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "double-click-tree-view",
      "language-javascript-jsx",
      "language-vue-component"
    ],
    "themes": [
      "one-dark-ui",
      "firewatch-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v3.0.0
firewatch-syntax, v1.0.1
language-pug, v0.0.17
language-vue, v0.13.0
pinned-tabs, v0.2.3

# Dev
No dev packages
```

**Comment by ericcornelissen** [comment]
I added a fix and updated the package!
