### ISSUE TITLE
Uncaught TypeError: Cannot read property 'parentNode' of undefined

### ISSUE THREAD

**Issue by craigiswayne** [ericcornelissen/pinned-tabs-for-atom#19]
[Enter steps to reproduce below:]

1. Added a folder to the workspace
2. Clicked on an image file from the added folder
3. The image preview in the RHS fine
4. try to close the tab by clicking the "x"

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [pinned-tabs](https://github.com/ericcornelissen/pinned-tabs-for-atom) package, v0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'parentNode' of undefined

```
At /Users/craigiswayne/.atom/packages/pinned-tabs/lib/pinned-tabs.coffee:109

TypeError: Cannot read property 'parentNode' of undefined
    at /Users/craigiswayne/.atom/packages/pinned-tabs/lib/pinned-tabs.coffee:109:26
    at Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/1.7.2/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.7.2/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.willDestroyPaneItem (/opt/homebrew-cask/Caskroom/atom/1.7.2/Atom.app/Contents/Resources/app.asar/src/pane-container.js:298:27)
    at Pane.module.exports.Pane.destroyItem (/opt/homebrew-cask/Caskroom/atom/1.7.2/Atom.app/Contents/Resources/app.asar/src/pane.js:630:17)
    at atom-tabs.TabBarView.onClick (/opt/homebrew-cask/Caskroom/atom/1.7.2/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:688:17)
```

### Commands

```
     -0:47.6.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:47.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:47.3.0 core:cancel (atom-text-editor.editor.is-focused)
  2x -0:47.1.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:46.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:45.1.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  8x -0:31.5.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  4x -0:30.3.0 core:move-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:29.6.0 tree-view:expand-item (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:29.1.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:28.8.0 tree-view:expand-item (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:28.3.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:23.4.0 tree-view:copy (li.file.entry.list-item.selected)
     -0:20.5.0 tree-view:paste (span.name.icon.icon-file-directory)
  2x -0:07.3.0 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:02.3.0 core:cancel (div.image-view)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.8
atom-minify, v0.7.5
file-icons, v1.7.15
html-entities, v0.4.0
markdown-preview-plus, v2.4.0
open-recent, v5.0.0
php-debug, v0.2.3
pinned-tabs, v0.3.0
sass-autocompile, v0.12.7
tablr, v1.3.1
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by ericcornelissen** [comment]
Thanks for reporting the bug. I fixed it, just update the package and everything should work fine! :smile:

**Comment by craigiswayne** [comment]
you are the best! thank you!
