### ISSUE TITLE
Failed to activate the pinned-tabs package

### ISSUE THREAD

**Issue by tommai78101** [ericcornelissen/pinned-tabs-for-atom#27]
**Steps to reproduce:**

1. Install Atom 1.16 and pinned-tabs package.
2. Pin the Atom Settings tab.
3. Restart Atom on 1.16.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [pinned-tabs](https://github.com/ericcornelissen/pinned-tabs-for-atom) package 1.0.0

### Stack Trace

Failed to activate the pinned-tabs package

```
At Cannot read property 'match' of undefined

TypeError: Cannot read property 'match' of undefined
    at Object.getItemID (/packages/pinned-tabs/lib/pinned-tabs.coffee:176:89)
    at /packages/pinned-tabs/lib/pinned-tabs.coffee:101:25)
    at /packages/pinned-tabs/lib/pinned-tabs.coffee:100:9)
    at Object.initTabs (/packages/pinned-tabs/lib/pinned-tabs.coffee:99:7)
    at Object.activate (/packages/pinned-tabs/lib/pinned-tabs.coffee:54:6)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:826:28
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.23 
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
autoupdate-packages 1.3.1 
busy-signal 1.4.1 
docblockr 0.9.4 
intentions 1.1.2 
language-babel 2.58.0 
language-batch 0.4.0 
linter 2.1.4 
linter-eslint 8.1.7 
linter-jshint 3.0.3 
linter-jsonlint 1.3.0 
linter-ui-default 1.2.4 
minimap 4.28.2 
minimap-pigments 0.2.2 
pigments 0.39.1 
pinned-tabs 1.0.0 
pretty-json 1.6.3 
Sublime-Style-Column-Selection 1.7.4 
```

**Comment by ericcornelissen** [comment]
Thanks for reporting! Unfortunately I'm not able to reproduce the bug... Did you really only have the Atom Settings tab pinned or possibly any other tabs?

**Comment by ani2life** [comment]
[Enter steps to reproduce:]

1. Open an existing file and 'Pin tab'
2. Open untitled tab (Cmd + N)
3. Close the untitled tab.
4. Uncaught TypeError: Cannot read property 'match' of undefined

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [pinned-tabs](https://github.com/ericcornelissen/pinned-tabs-for-atom) package 1.0.0


### Stack Trace

Uncaught TypeError: Cannot read property 'match' of undefined

```
At /Users/ani2life/.atom/packages/pinned-tabs/lib/pinned-tabs.coffee:176

TypeError: Cannot read property 'match' of undefined
    at Object.getItemID (/packages/pinned-tabs/lib/pinned-tabs.coffee:176:89)
    at /packages/pinned-tabs/lib/pinned-tabs.coffee:92:75
    at Array.filter (native)
    at /packages/pinned-tabs/lib/pinned-tabs.coffee:92:51
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PaneContainer.module.exports.PaneContainer.willDestroyPaneItem (/app.asar/src/pane-container.js:300:27)
    at Pane.module.exports.Pane.destroyItem (/app.asar/src/pane.js:651:16)
    at TabBarView.module.exports.TabBarView.closeTab (/app.asar/node_modules/tabs/lib/tab-bar-view.js:333:26)
    at HTMLDivElement.TabView.didClickCloseIcon (/app.asar/node_modules/tabs/lib/tab-bar-view.js:222:19)
```

### Commands

```
     -1:04.4.0 core:move-down (input.hidden-input)
     -1:04.3.0 core:move-left (input.hidden-input)
     -1:04.0 core:backspace (input.hidden-input)
     -1:03.8.0 core:move-down (input.hidden-input)
  5x -1:03.6.0 core:move-right (input.hidden-input)
     -1:02.1.0 core:backspace (input.hidden-input)
     -1:02.0 core:move-down (input.hidden-input)
     -1:01.8.0 core:move-left (input.hidden-input)
     -1:01.4.0 core:backspace (input.hidden-input)
  2x -1:01.2.0 core:move-down (input.hidden-input)
     -0:59.5.0 core:save (input.hidden-input)
     -0:55.7.0 core:move-down (input.hidden-input)
     -0:44.9.0 pane:show-item-2 (input.hidden-input)
     -0:43.3.0 pane:show-item-3 (input.hidden-input)
     -0:40.9.0 core:close (input.hidden-input)
     -0:23.6.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
api-docs 0.0.6 
atom-beautify 0.29.23 
atom-fix-path 0.1.0 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
build 0.67.0 
build-gulp 0.11.0 
busy 0.7.0 
busy-signal 1.4.1 
chester-atom-syntax 0.1.1 
custom-invisibles 0.1.2 
devdocs 0.2.1 
docblockr 0.9.4 
file-icons 2.1.4 
fonts 2.0.0 
git-diff-details 1.4.0 
git-log 0.4.1 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
hyperclick 0.0.40 
imdone-atom 2.2.6 
improved-autocomplete-php 1.1.1 
improved-chester-atom-syntax 0.3.0 
intentions 1.1.2 
linter 2.1.4 
linter-phpcs 1.6.2 
linter-ui-default 1.2.4 
markdown-preview-enhanced 0.12.1 
multi-cursor 2.1.5 
php-integrator-annotations 1.1.1 
php-integrator-autocomplete-plus 1.5.0 
php-integrator-base 2.1.11 
php-integrator-call-tips 1.2.1 
php-integrator-linter 1.3.0 
php-integrator-navigation 1.1.2 
php-integrator-refactoring 1.3.1 
php-integrator-tooltips 1.1.5 
pigments 0.39.1 
pinned-tabs 1.0.0 
project-manager 3.3.4 
qolor 0.4.1 
script 3.14.1 
split-diff 1.3.0 
tabs-to-spaces 1.0.3 
```

**Comment by ericcornelissen** [comment]
Thanks @ani2life, I was able to reproduce that one. I fixed the issue you described and the fix should also solve @tommai78101's issue. I'll publish the fix later today 😄

**Comment by tommai78101** [comment]
Thanks again for the fix. It's now working. Sorry for not responding, due to the weekends.

**Comment by ericcornelissen** [comment]
You're welcome and no problem! 😄

**Comment by donnikitos** [comment]
[Enter steps to reproduce:]

1. Disable "pinned-tabs" in Settings
2. Enable "pinned-tabs" in Settings

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: "Fedora release
**Thrown From**: [pinned-tabs](https://github.com/ericcornelissen/pinned-tabs-for-atom) package 2.0.2


### Stack Trace

Failed to activate the pinned-tabs package

```
At Can't register a command with non-function callback.

Error: Can't register a command with non-function callback.
    at CommandRegistry.module.exports.CommandRegistry.add (/usr/share/atom/resources/app/src/command-registry.js:63:21)
    at PinnedTabs.setCommands (/packages/pinned-tabs/lib/pinned-tabs.js:194:23)
    at PinnedTabs.activate (/packages/pinned-tabs/lib/pinned-tabs.js:79:10)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:253:25)
    at /usr/share/atom/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:21)
    at /usr/share/atom/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:645:40)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:519:35
    at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:338:17)
    at /usr/share/atom/resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -5:02.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
  2x -3:33.9.0 pinned-tabs:pin-selected (li.texteditor.tab.sortable.right-clicked)
```

### Non-Core Packages

```
angularjs 0.5.1 
atom-bootstrap4 1.4.0 
atom-typescript 11.0.9 
autocomplete-clang 0.11.4 
build 0.70.0 
busy 0.7.0 
busy-signal 1.4.3 
color-picker 2.2.5 
file-icons 2.1.15 
intentions 1.1.5 
keyboard-localization 1.5.0 
language-haxe 0.6.0 
language-htaccess 0.1.1 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.10 
minimap 4.29.7 
pinned-tabs 2.0.2 
platformio-ide 2.0.0-rc.4 
platformio-ide-debugger 1.2.4 
platformio-ide-terminal 2.7.0 
sync-settings 0.8.3 
tool-bar 1.1.0 
```

**Comment by tommai78101** [comment]
> Updated Atom to 1.23.1 x64 -> everything works fine again

*Wipes sweating head*

**Comment by ericcornelissen** [comment]
> *Wipes sweating head*

😆

For real though, I'm glad you commented because otherwise I missed it 👍 I updated @donnikitos comment to make the "Updated Atom ..." edit a bit more visible
