### ISSUE TITLE
Uncaught TypeError: Cannot read property 'itemAtIndex' of undefined

### ISSUE THREAD

**Issue by ChuJung** [ericcornelissen/pinned-tabs-for-atom#31]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [pinned-tabs](https://github.com/ericcornelissen/pinned-tabs-for-atom) package 1.0.3

### Stack Trace

Uncaught TypeError: Cannot read property 'itemAtIndex' of undefined

```
At C:\Users\ChuJung\.atom\packages\pinned-tabs\lib\pinned-tabs.coffee:185

TypeError: Cannot read property 'itemAtIndex' of undefined
    at Object.getEditor (/packages/pinned-tabs/lib/pinned-tabs.coffee:185:16)
    at Object.pinSelected (/packages/pinned-tabs/lib/pinned-tabs.coffee:136:13)
    at /packages/pinned-tabs/lib/pinned-tabs.coffee:68:73)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/app.asar/src/atom-environment.js:1185:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:325:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -9:59.8.0 tabs:split-right (div.title.icon.icon-markdown)
     -7:21 core:paste (input.hidden-input)
     -7:20.2.0 core:select-all (input.hidden-input)
     -7:19.2.0 core:paste (input.hidden-input)
     -6:59.3.0 core:confirm (input.hidden-input)
     -0:39.4.0 pinned-tabs:pin-selected (li.tab.sortable.active.right-clicked)
```

### Non-Core Packages

```
atom-i18n 0.8.0 
clipboard-plus 0.5.1 
copy-file-contents 0.3.0 
counter 0.3.5 
expose 0.14.0 
file-icons 2.1.4 
filter-syntax 0.3.0 
highlight-selected 0.13.1 
language-markdown 0.22.0 
languagetool 0.1.1 
light-bint-ui 1.0.10 
markdown-scroll-sync 2.1.2 
markdown-writer 2.6.5 
minimap 4.28.2 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-highlight-selected 4.6.1 
multi-wrap-guide 0.28.4 
pdf-view 0.57.0 
pinned-tabs 1.0.3 
project-manager 3.3.4 
simple-drag-drop-text 0.3.4 
sync-settings 0.8.1 
tab-switcher 1.5.4 
tablr 1.8.3 
typewriter-sounds 0.1.0 
web-view 3.0.0 
```

**Comment by ericcornelissen** [comment]
I think I was able to fix this issue in d95e202 :tada:

However, I changed quite an important part of the package in order to get this working, but the new solution should work more reliably... Would you mind cloning the repo into your `~/.atom/package` and verify the issue has been resolved?
