### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getFileName' of null

### ISSUE THREAD

**Issue by tfp1** [ericcornelissen/pinned-tabs-for-atom#39]
[Enter steps to reproduce:]

1. Shutdown laptop with Atom open. Had 3 txt documents open, 1 markdown preview open. One of the text documents had been pinned
2. Atom launched with startup (Pick up where you left off...)
3. Closed one of the text files without issue
4. Attempted to close the non-pinned markdown preview and received the following error

Was able to close all documents successfully once I saved the pinned file and closed it

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [pinned-tabs](https://github.com/ericcornelissen/pinned-tabs-for-atom) package 1.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getFileName' of null

```
At /Users/tfprice/.atom/packages/pinned-tabs/lib/pinned-tabs.coffee:214

TypeError: Cannot read property 'getFileName' of null
    at Object.getItemID (/packages/pinned-tabs/lib/pinned-tabs.coffee:214:68)
    at /packages/pinned-tabs/lib/pinned-tabs.coffee:114:75
    at Array.filter (native)
    at /packages/pinned-tabs/lib/pinned-tabs.coffee:114:51
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.willDestroyPaneItem (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:274:24)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:699:22)
    at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:683:18)
    at Workspace.closeActivePaneItemOrEmptyPaneOrWindow (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1716:48)
    at HTMLElement.core:close (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:233:38)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  3x -1:41.7.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-formatter-jsbeautify 1.1.2 
auto-update-packages 1.0.1 
color-tabs 0.1.8 
custom-title 1.0.1 
default-language 0.3.0 
highlight-selected 0.13.1 
json-converter 0.2.4 
language-markdown 0.25.1 
markdown-pdf 2.1.0 
markdown-preview-plus 2.4.16 
minimap 4.29.7 
one-o-eight-syntax 0.29.1 
open-recent 5.0.0 
pinned-tabs 1.3.0 
qolor 0.4.2 
remove-whitespace 0.2.1 
sort-lines 0.18.0 
tablr 1.8.3 
todo-show 2.1.0 
wordcount 2.10.4 
```

**Comment by ericcornelissen** [comment]
Thank you for reporting, I'm looking into it. Seems to be related to #22.
