### ISSUE TITLE
Uncaught TypeError: Cannot read property 'findIndex' of undefined

### ISSUE THREAD

**Issue by rajkishoreworks** [ericcornelissen/pinned-tabs-for-atom#45]
[steps to reproduce:]

1. Split the screen into 2 panes
2. Drag pinned tab from one pane to another pane.

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [pinned-tabs](https://github.com/ericcornelissen/pinned-tabs-for-atom) package 2.0.2

### Stack Trace

Uncaught TypeError: Cannot read property 'findIndex' of undefined

```
At C:\Users\rgu106\.atom\packages\pinned-tabs\lib\state.js:151

TypeError: Cannot read property 'findIndex' of undefined
    at PinnedTabsState.removePaneItem (/packages/pinned-tabs/lib/state.js:151:29)
    at setTimeout (/packages/pinned-tabs/lib/pinned-tabs.js:251:28)
```

### Commands

```
     -4:28.8.0 core:move-down (input.hidden-input)
     -1:47.1.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -1:41.4.0 core:confirm (input.hidden-input)
     -1:38 tree-view:add-folder (span.name.icon.icon-file-directory)
     -1:33.5.0 core:confirm (input.hidden-input)
     -1:24.9.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -1:21.4.0 core:confirm (input.hidden-input)
     -1:16 tree-view:add-file (div.header.list-item)
     -1:13.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-typescript 11.0.10 
file-icons 2.1.15 
highlight-selected 0.13.1 
impex-aligner 2.1.0 
language-batch 0.4.0 
language-ejs 0.4.0 
language-impex 1.0.1 
open-in-browser 0.5.2 
open-path 0.3.6 
open-terminal-here 2.3.1 
open-unsupported-files 1.0.20 
pinned-tabs 2.0.2 
react 0.17.0 
```

**Comment by ericcornelissen** [comment]
Thank you for reporting, a minor change fixed it 👍
